<?php
$e = function ($v) { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); };
$isShop = $slug === 'shop'; $isTicket = $slug === 'ticket';
$heroImage = $demo['hero_image'] ?? '';
$visuals = [
    'shop' => ['/assets/images/portfolio/product-champagne-jacket.jpg','/assets/images/portfolio/product-noir-trouser.jpg','/assets/images/portfolio/product-obsidian-shirt.jpg'],
    'cafe' => ['/assets/images/portfolio/cafe-coffee.jpg','/assets/images/portfolio/cafe-food.jpg','/assets/images/portfolio/cafe-hero.jpg'],
    'realestate' => ['/assets/images/portfolio/estate-hero.jpg','/assets/images/portfolio/architecture-hero.jpg','/assets/images/portfolio/estate-hero.jpg'],
];
$itemVisuals = $visuals[$slug] ?? [$heroImage, $heroImage, $heroImage];
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?= $e($description) ?>"><link rel="canonical" href="https://majedmansouri.ir/<?= $e($slug) ?>"><meta property="og:title" content="<?= $e($title) ?>"><meta property="og:description" content="<?= $e($description) ?>"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/images/admin-icon-192.png"><title><?= $e($title) ?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800&family=Cormorant+Garamond:wght@500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="/assets/css/portfolio.css"><link rel="stylesheet" href="/assets/css/demo-themes.css"></head>
<body class="demo-page demo-<?= $e($slug) ?>" data-demo="<?= $e($slug) ?>"><div class="ambient"></div><header class="demo-nav" data-guide="ناوبری|دسترسی سریع به بخش‌های کلیدی سایت، برند و اقدام‌های اصلی."><a class="brand" href="/<?= $e($slug) ?>"><?= $e($demo['name']) ?><small><?= $e($demo['label']) ?></small></a><button class="menu-toggle" aria-label="باز کردن منو"><i class="fa-solid fa-bars"></i></button><nav><a href="#services"><?= $isShop ? 'محصولات' : 'خدمات' ?></a><a href="#about">درباره ما</a><a href="#contact">تماس</a></nav><div class="nav-actions"><?php if ($isShop): ?><a class="cart-link" href="/shop/cart"><i class="fa-solid fa-bag-shopping"></i><b data-cart-count>۰</b></a><?php endif; ?><button class="guide-toggle" aria-pressed="false"><i class="fa-regular fa-compass"></i> راهنمای طراحی</button></div></header>
<main><?php if ($subpage): ?><section class="inner-page" data-guide="صفحه داخلی|این صفحه برای تکمیل مسیر کاربر پس از انتخاب یک آیتم طراحی شده است."><p class="eyebrow"><?= $e($demo['label']) ?></p><h1><?= $subpage === 'cart' ? 'سبد خرید شما' : ($subpage === 'checkout' ? 'تکمیل سفارش' : 'جزئیات و انتخاب') ?></h1><p>این یک مسیر تعاملی نمونه است. اطلاعات در همین مرورگر نگهداری می‌شود و هیچ پرداخت واقعی انجام نخواهد شد.</p><?php if ($subpage === 'cart'): ?><div class="cart-view" data-cart-view></div><a class="button primary" href="/shop/checkout">ادامه و تکمیل سفارش</a><?php elseif ($subpage === 'checkout'): ?><form class="booking-form success-form"><label>نام و نام خانوادگی<input required placeholder="مثلاً نازنین احمدی"></label><label>شماره همراه<input required inputmode="tel" placeholder="۰۹۱۲... "></label><button class="button primary">ثبت سفارش آزمایشی</button></form><?php else: ?><div class="detail-showcase"><div class="image-placeholder large"><i class="fa-solid <?= $e($demo['icon']) ?>"></i><span><?= $e($demo['image']) ?></span></div><div><h2><?= $e($demo['items'][0]['نام']) ?></h2><p><?= $e($description) ?></p><button class="button primary add-cart" data-name="<?= $e($demo['items'][0]['نام']) ?>" data-price="<?= $e($demo['items'][0]['قیمت']) ?>">انتخاب و ادامه</button></div></div><?php endif; ?></section><?php else: ?>
<section class="demo-hero" data-guide="بخش Hero|معرفی سریع برند و مهم‌ترین پیام صفحه. محتوا: عنوان، توضیح کوتاه، تصویر اصلی و دکمه اقدام."><div class="hero-copy"><p class="eyebrow"><?= $e($demo['label']) ?> · تجربه‌ای با جزئیات</p><h1><?= $e($demo['hero']) ?></h1><p><?= $e($demo['description']) ?></p><div class="hero-actions"><a class="button primary" href="#services"><?= $e($demo['cta']) ?> <i class="fa-solid fa-arrow-left"></i></a><a class="button ghost" href="#about">بیشتر بدانید</a></div><div class="trust"><span><b>۴.۹</b> رضایت کاربران</span><span><b>۲۴/۷</b> همراه شما</span></div></div><div class="hero-visual image-placeholder has-photo" data-guide-image="تصویر اصلی|نمایش فضای اصلی برند|16:9|1600 × 900|WebP / JPG"><?php if ($heroImage): ?><img src="<?= $e($heroImage) ?>" alt="<?= $e($demo['image']) ?>" fetchpriority="high"><?php endif; ?><span><?= $e($demo['image']) ?></span><small>نسبت پیشنهادی: ۱۶:۹</small></div></section>
<section id="services" class="demo-section" data-guide="کارت‌های محتوا|نمایش خلاصه اطلاعات قابل مقایسه. هر کارت شامل تصویر، عنوان، توضیح، قیمت یا اطلاعات کلیدی و CTA است."><div class="section-heading"><div><p class="eyebrow"><?= $isShop ? 'انتخاب‌های امروز' : 'آنچه ارائه می‌کنیم' ?></p><h2><?= $isShop ? 'محصولات منتخب' : ($isTicket ? 'رویدادهای محبوب' : 'انتخاب‌های ویژه') ?></h2></div><a href="/<?= $e($slug) ?>/<?= $isShop ? 'products' : 'events' ?>">مشاهده همه <i class="fa-solid fa-arrow-left"></i></a></div><div class="item-grid"><?php foreach ($demo['items'] as $index => $item): ?><article class="item-card" data-category="<?= $e($item['category']) ?>"><div class="item-image has-photo"><img src="<?= $e($itemVisuals[$index] ?? $heroImage) ?>" alt="<?= $e($item['نام']) ?>" loading="lazy"><span><?= $e($item['tag']) ?></span><small><?= $e($item['category']) ?></small></div><div class="item-content"><div><p><?= $e($item['category']) ?></p><h3><?= $e($item['نام']) ?></h3></div><strong><?= $e($item['قیمت']) ?><?= $isShop ? ' تومان' : '' ?></strong><div class="item-bottom"><span>★ ۴.۸</span><?php if ($isShop): ?><button class="add-cart" data-name="<?= $e($item['نام']) ?>" data-price="<?= $e($item['قیمت']) ?>"><i class="fa-solid fa-plus"></i> افزودن</button><?php elseif ($isTicket): ?><a href="/ticket/event/concert">انتخاب بلیت</a><?php else: ?><button class="open-modal" data-item="<?= $e($item['نام']) ?>">مشاهده</button><?php endif; ?></div></div></article><?php endforeach; ?></div></section>
<section id="about" class="split-section" data-guide="بخش معرفی|ایجاد اعتماد با بیان مختصر ارزش برند، آمار و یک تصویر مکمل."><div class="image-placeholder compact" data-guide-image="تصویر معرفی|نمایش جزئیات فضا یا تیم|4:5|1000 × 1250|WebP / JPG"><i class="fa-solid fa-wand-magic-sparkles"></i><span>تصویر مکمل برند</span></div><div><p class="eyebrow">یک تجربه متمایز</p><h2>جزئیات کوچک، تفاوت‌های بزرگ می‌سازند.</h2><p>در این نمونه، ساختار محتوا طوری چیده شده که کاربر بدون سردرگمی، پیشنهاد اصلی را ببیند و برای قدم بعدی تصمیم بگیرد.</p><div class="stats"><div><b>۱۲+</b><span>سال تجربه</span></div><div><b>۳۰۰</b><span>مشتری همراه</span></div><div><b>۹۸٪</b><span>رضایت</span></div></div></div></section>
<section class="testimonial" data-guide="نظرات مشتریان|اثبات اجتماعی برای کاهش تردید کاربر در مرحله تصمیم‌گیری."><i class="fa-solid fa-quote-right"></i><blockquote>«همه‌چیز، از اولین نگاه تا آخرین کلیک، ساده و قابل اعتماد بود. دقیقاً همان تجربه‌ای که انتظارش را داشتیم.»</blockquote><p>— نسترن م.، مشتری مجموعه</p></section>
<section id="contact" class="cta-section" data-guide="بخش CTA|هدایت کاربر به مهم‌ترین اقدام صفحه؛ فرم کوتاه و یک دعوت شفاف."><div><p class="eyebrow">قدم بعدی</p><h2><?= $e($demo['cta']) ?>، همین حالا</h2><p>چند اطلاعات کوتاه را وارد کنید؛ این فرم در دمو، پاسخ نمایشی نشان می‌دهد.</p></div><form class="booking-form success-form"><label>نام شما<input required placeholder="نام و نام خانوادگی"></label><label><?= $isTicket ? 'ایمیل' : 'شماره همراه' ?><input required placeholder="برای هماهنگی"></label><button class="button primary">ارسال درخواست</button></form></section>
<section class="faq-section" data-guide="پرسش‌های متداول|پاسخ به ابهام‌های رایج پیش از اقدام نهایی کاربر."><p class="eyebrow">پرسش‌های متداول</p><h2>سؤال‌هایی که شاید برای شما هم پیش بیاید</h2><details><summary>این سرویس چگونه کار می‌کند؟ <i class="fa-solid fa-plus"></i></summary><p>کاربر اطلاعات مورد نیاز را انتخاب می‌کند و درخواست خود را در چند گام کوتاه ثبت می‌کند.</p></details><details><summary>آیا امکان تغییر انتخاب وجود دارد؟ <i class="fa-solid fa-plus"></i></summary><p>بله، همه انتخاب‌ها پیش از ثبت نهایی قابل ویرایش هستند.</p></details></section><?php endif; ?></main>
<footer class="demo-footer"><div><a class="brand" href="/<?= $e($slug) ?>"><?= $e($demo['name']) ?></a><p>این یک دموی طراحی توسط مجید منصوری است.</p></div><div><a href="/">بازگشت به پورتفولیو</a><a href="#contact">تماس با ما</a></div></footer><aside class="guide-panel" aria-live="polite"><button class="close-guide" aria-label="بستن راهنما">×</button><p class="eyebrow">راهنمای طراحی</p><h3>روی بخش‌ها حرکت کنید</h3><p>هر بخش با کادر ظریف مشخص می‌شود. جزئیات مورد نیاز برای جایگزینی محتوا در همین‌جا نمایش داده خواهد شد.</p></aside><div class="toast" role="status"></div><script src="/assets/js/portfolio.js" defer></script></body></html>
