<?php $title = 'مجید منصوری | طراح و توسعه‌دهنده وب'; ?>
<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="پورتفولیوی مجید منصوری؛ طراحی و توسعه تجربه‌های دیجیتال فارسی.">
<link rel="canonical" href="https://majedmansouri.ir/"><meta property="og:title" content="<?= $title ?>"><meta property="og:description" content="پورتفولیوی طراحی وب مجید منصوری"><meta property="og:image" content="/assets/images/portfolio/hero-fashion.jpg"><title><?= $title ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800&family=Cormorant+Garamond:wght@500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="/assets/css/portfolio.css"><link rel="stylesheet" href="/assets/css/home-portfolio.css"></head>
<body class="portfolio-page editorial-home"><div class="home-noise"></div>
<header class="home-nav"><a class="home-brand" href="/"><span>MAJED</span><strong>MANSOURI</strong></a><nav><a href="#projects">پروژه‌ها</a><a href="#about">درباره من</a><a href="#contact">همکاری</a></nav><a class="home-menu" href="#projects"><span>مشاهده دموها</span><i class="fa-solid fa-arrow-left"></i></a></header>
<main>
<section class="editorial-hero"><div class="hero-art"><img src="/assets/images/portfolio/hero-fashion.jpg" alt="نمونه‌ای از طراحی وب فروشگاه مد" fetchpriority="high"><div class="hero-art-shade"></div><p class="vertical-mark">SELECTED DIGITAL EXPERIENCES — 2026</p></div><div class="hero-content"><p class="home-kicker">طراح وب و توسعه‌دهنده وب</p><h1>تجربه‌های دیجیتال<br>برای برندهایی که<br><em>متفاوت فکر می‌کنند.</em></h1><p class="hero-lede">من مجید منصوری هستم. بین استراتژی، طراحی بصری و کد، مسیرهایی می‌سازم که هم دیده می‌شوند و هم نتیجه می‌سازند.</p><div class="home-actions"><a href="#projects" class="home-button dark">مشاهده پروژه‌ها <i class="fa-solid fa-arrow-left"></i></a><a href="#about" class="text-button">رویکرد من <i class="fa-solid fa-arrow-down"></i></a></div></div><div class="hero-index"><span>01</span><i></i><span>08</span></div></section>
<section id="projects" class="projects-intro"><p class="home-kicker">انتخاب کنید، تجربه کنید</p><div><h2>هر پروژه یک <em>دموی زنده</em> است.</h2><p>روی هر پروژه کلیک کنید، تجربه واقعی آن را ببینید و با فعال‌کردن «راهنمای طراحی» منطق UI و محتوای موردنیاز را بررسی کنید.</p></div></section>
<section class="featured-work shop-work"><a href="/shop" class="work-image"><img src="/assets/images/portfolio/hero-fashion.jpg" alt="دموی فروشگاه مد"><span class="image-number">01 / SHOP</span></a><div class="work-copy"><p class="home-kicker">فروشگاه اینترنتی · آتریوم</p><h2>فروشگاهی برای<br><em>انتخاب‌های دقیق.</em></h2><p>نمایش محصول، سبد خرید، مسیر پرداخت و تجربه موبایل؛ برای برندهایی که می‌خواهند محصولشان همان‌قدر که خوب است، خوب هم دیده شود.</p><div class="work-links"><a href="/shop">ورود به فروشگاه <i class="fa-solid fa-arrow-left"></i></a><a href="/shop?guide=1">راهنمای طراحی</a></div></div></section>
<section class="project-mosaic">
<a href="/cafe" class="mosaic-card cafe-card"><img src="/assets/images/portfolio/cafe-hero.jpg" alt="دموی کافی‌شاپ"><span>02</span><div><p>کافه و رستوران</p><h3>کافه روبرو</h3><i class="fa-solid fa-arrow-left"></i></div></a>
<a href="/realestate" class="mosaic-card estate-card"><img src="/assets/images/portfolio/estate-hero.jpg" alt="دموی املاک"><span>03</span><div><p>املاک و مستغلات</p><h3>خانه‌رو</h3><i class="fa-solid fa-arrow-left"></i></div></a>
<a href="/medical" class="mosaic-card clinic-card"><img src="/assets/images/portfolio/clinic-hero.jpg" alt="دموی مرکز پزشکی"><span>04</span><div><p>سلامت و پزشکی</p><h3>مرکز سپید</h3><i class="fa-solid fa-arrow-left"></i></div></a>
</section>
<section class="other-demos"><div class="section-rule"><p class="home-kicker">پروژه‌های بیشتر</p><span></span></div><div class="demo-list"><?php $quick = ['ticket'=>'فروش بلیت و رویداد','company'=>'وب‌سایت شرکتی','restaurant'=>'رستوران','hotel'=>'هتل و اقامت']; $i=5; foreach($quick as $slug=>$label): ?><a href="/<?= $slug ?>"><b>0<?= $i++ ?></b><span><?= $label ?></span><small><?= htmlspecialchars($demos[$slug]['name']) ?></small><i class="fa-solid fa-arrow-left"></i></a><?php endforeach; ?></div></section>
<section id="about" class="about-editorial"><div class="portrait-wrap"><img src="/assets/images/majed-mansouri.webp" alt="مجید منصوری"><span>MJ / MM</span></div><div class="about-copy"><p class="home-kicker">درباره من</p><h2>طراحی خوب، فقط زیبا نیست؛ <em>مسیر را روشن می‌کند.</em></h2><p>برای من، طراحی از یک ظاهر شروع نمی‌شود. از فهمیدن برند، شناخت مخاطب و پیدا کردن دقیق‌ترین راه برای رساندن یک پیام شروع می‌شود. سپس با ترکیب محتوا، UI/UX و توسعه، آن را به تجربه‌ای قابل استفاده تبدیل می‌کنم.</p><div class="numbers"><div><b>+۳۰</b><span>پروژه منتخب</span></div><div><b>۳</b><span>حوزه تخصصی</span></div><div><b>∞</b><span>توجه به جزئیات</span></div></div></div></section>
<section id="contact" class="contact-editorial"><p class="home-kicker">همکاری بعدی</p><h2>ایده‌ای دارید که باید<br><em>درست دیده شود؟</em></h2><a href="mailto:hello@majedmansouri.ir">hello@majedmansouri.ir <i class="fa-solid fa-arrow-left"></i></a></section>
</main><footer class="home-footer"><a class="home-brand" href="/"><span>MAJED</span><strong>MANSOURI</strong></a><span>© <?= date('Y') ?> تمامی حقوق محفوظ است.</span><a href="#projects">بازگشت به پروژه‌ها ↑</a></footer>
</body></html>
